on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt install check
        name: Install check unit test framework
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Run unit tests
        run: ctest --output-on-failure --test-dir build
