on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.os == 'ubuntu-latest'}}
        name: Install valgrind
        run: |
          sudo apt update
          sudo apt install valgrind
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Run unit tests
        run: ctest --output-on-failure --test-dir build
      - name: Run memory check
        run: ctest -T MemCheck --test-dir build
