on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check for memory leaks
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install valgrind
        name: Install valgrind
      - run: sudo apt install check
        name: Install check unit test framework
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Run memcheck
        run: |
          ctest \
          --overwrite MemoryCheckCommandOptions="--leak-check=full" \
          -T memcheck --test-dir build
      - run: ls -l build/Testing/Temporary/*
